In [5]:
import numpy as np

#create matrices
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print("matrix a")
print(a)
print(" ")
print("matrix b")
print(b)

#addition
c=a+b
print("Matrix addition")
print(c)
#substraction
e=a-b
print("Matrix substraction")
print(e)

#matrix mulltiplication
f=np.dot(a,b)
print("Matrix multiplication")
print(f)

#transpose
a_t=a.T
print("Matrix Transpose")
print(a_t)

matrix a
[[1 2]
 [3 4]]
 
matrix b
[[5 6]
 [7 8]]
Matrix addition
[[ 6  8]
 [10 12]]
Matrix substraction
[[-4 -4]
 [-4 -4]]
Matrix multiplication
[[19 22]
 [43 50]]
Matrix Transpose
[[1 3]
 [2 4]]


In [1]:
#with SVD
import numpy as np
#create a sample matrix
X=np.array([[1,2,3],[4,5,6],[7,8,9]])

#perform SVD
U,S,VT=np.linalg.svd(X)
n_components=2
X_reconstructed=np.dot(U[:,:n_components],np.dot(np.diag(S[:n_components]),VT[:n_components,:]))
print("Original Matrix:")
print(X)
print("\nReconstructed Matrix(with reduced dimensions):")
print(X_reconstructed)

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Reconstructed Matrix(with reduced dimensions):
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
